#### Conv-TasNet Setting
name: Conv_Tasnet
# gpu_ids: [0,1,2,3,6,7]
gpu_ids: [0]
epochs: 100

#### Dataset Configure
datasets:
  num_workers: 4
  batch_size: 6
  fs: 8000
  # chunk_len: 4
  # chunk_size: 32000 #### fs*chunk_len
  train:
    mix_scp: /mnt/Conv-TasNet/Conv_TasNet_Pytorch/data/audio_scp_8k/train_100/clean/tr_mix.scp
    ref_scp: 
      - /mnt/Conv-TasNet/Conv_TasNet_Pytorch/data/audio_scp_8k/train_100/tr_s1.scp
      - /mnt/Conv-TasNet/Conv_TasNet_Pytorch/data/audio_scp_8k/train_100/tr_s2.scp
    text_path1: /mnt/Conv-TasNet/Conv_TasNet_TSE/text/train_100/train_100_spk1.csv
    text_path2: /mnt/Conv-TasNet/Conv_TasNet_TSE/text/train_100/train_100_spk2.csv
    sr: 8000
  val:
    mix_scp: /mnt/Conv-TasNet/Conv_TasNet_Pytorch/data/audio_scp_8k/dev/clean/cv_mix.scp
    ref_scp: 
      - /mnt/Conv-TasNet/Conv_TasNet_Pytorch/data/audio_scp_8k/dev/cv_s1.scp
      - /mnt/Conv-TasNet/Conv_TasNet_Pytorch/data/audio_scp_8k/dev/cv_s2.scp
    text_path1: /mnt/Conv-TasNet/Conv_TasNet_TSE/text/val/val_spk1.csv
    text_path2: /mnt/Conv-TasNet/Conv_TasNet_TSE/text/val/val_spk2.csv
    sr: 8000

#### training settings: learning rate scheme, loss
train:
  optimizer: adam
  min_lr: !!float 1e-8
  patience: 2
  factor: 0.5
  logging_period: 200
  clip_norm: 200
  num_epochs: 100
  checkpoint: Conv-TasNet-clean100-text

optimizer_kwargs:
  lr: !!float 1e-3
  weight_decay: !!float 1e-5

#### network configure
net_conf:
  N: 512
  L: 16
  B: 128
  H: 512
  P: 3
  X: 8
  R: 3
  norm: gln
  num_spks: 2
  activate: relu
  causal: false
  text_model_name: "bert-base-uncased"  # 新增：文本模型名称
  pooling_method: "cls"         # 新增：池化方法
  attn_dim: 256
  ##skip_con: false

#### resume model
resume:
  path: /mnt/Conv-TasNet/Conv_TasNet_Pytorch
  resume_state: false